CREATE TABLE IF NOT EXISTS Tarefas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR NOT NULL,
    descricao VARCHAR NOT NULL,
    data_tarefa TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    concluida boolean
)
